modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="ddoity"
version="1.0.0"
displayName="ddoity"
credits="此模组谨以献给 §b美好的 §bYYDS §e7B8"
displayURL="https://www.cliffordsecondary.com/staff/western-english-staff/"
logoFile="logo.png"
authors="Tony佟羽"
description='''
§e§l再见，7B8
§e§l你好，8B8
D的自述：§e§oGreetings, this is my eighth year of teaching at Clifford School Secondary Bilingual; I have taught for over fourteen years. I am a life-long learner, and I am a certified and professional educator. I am a graduate: of the American College of Education with a Master of Education in Teaching English Learners; Ohio University, with a Bachelor of Science in Adolescent to Young Adult Education with a minor in the Social Studies, a dual Bachelor of Arts in History and Political Science; and an Associate of Applied Arts; Belmont Technical College, an Associate of Science in Business Management; University of Anaheim in California, with certification in Teaching English as a Second or Other Language (TESOL); the University of South Carolina, with certification in Gifted and Talented Education (GT); and Clemson University, with certification in Advanced Placement United States History (APUSH). I am also a member of two academic honor societies: Phi Alpha Theta for History; and Kappa Delta Pi for Education. My beautiful wife who is the best teacher I know, Mrs. Doty, is the 4.1 teacher in the Bilingual Upper Elementary. She has already told me much about all of you. I hope you all have a great experience.  
'''

[[dependencies.ddoity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




